import { createClient } from '@supabase/supabase-js'
import fs from 'node:fs'
import path from 'node:path'

function loadEnv() {
  const envPath = path.join(process.cwd(), '.env.test.local')
  if (!fs.existsSync(envPath)) {
    console.error('FATAL: .env.test.local not found. Copy .env.test.local.example and fill it in.')
    process.exit(2)
  }
  const env = {}
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trim = line.trim()
    if (!trim || trim.startsWith('#')) continue
    const eq = trim.indexOf('=')
    if (eq < 0) continue
    env[trim.slice(0, eq).trim()] = trim.slice(eq + 1).trim()
  }
  for (const k of ['SUPABASE_URL', 'SUPABASE_ANON_KEY']) {
    if (!env[k]) {
      console.error(`FATAL: ${k} missing in .env.test.local`)
      process.exit(2)
    }
  }
  return env
}

export const env = loadEnv()
export const TEST_PREFIX = '[TEST]'

export async function signInAs(role) {
  const u = env[`TEST_${role.toUpperCase()}_USERNAME`]
  const p = env[`TEST_${role.toUpperCase()}_PASSWORD`]
  if (!u || !p) {
    console.error(`FATAL: TEST_${role.toUpperCase()}_USERNAME / _PASSWORD missing in .env.test.local`)
    process.exit(2)
  }
  const client = createClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  })
  const { data, error } = await client.auth.signInWithPassword({
    email: `${u}@martin.local`,
    password: p,
  })
  if (error) {
    console.error(`FATAL: sign-in failed for ${role}: ${error.message}`)
    console.error('Check that the Auth user exists and password matches.')
    process.exit(2)
  }
  return { client, user: data.user }
}

export function makeTestSupplier(scope, branchId = null) {
  return {
    name: `${TEST_PREFIX} ${scope}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`,
    scope,
    branch_id: branchId,
    contact: 'rls-test',
    phone: '0000000000',
    category: 'test',
    notes: 'auto-generated by tests/rls; safe to delete',
    active: true,
  }
}

export async function cleanupTestSuppliers(adminClient) {
  // Run with admin client so we can clean any leftover rows regardless of scope.
  const { error } = await adminClient.from('suppliers_new').delete().like('name', `${TEST_PREFIX}%`)
  if (error) console.warn(`cleanup warning: ${error.message}`)
}

const state = { passed: 0, failed: 0, failures: [] }

export function assertOk(result, name) {
  if (!result.error) {
    console.log(`  PASS  ${name}`)
    state.passed++
  } else {
    console.log(`  FAIL  ${name}`)
    console.log(`        ${result.error.message}`)
    state.failed++
    state.failures.push(`${name}: ${result.error.message}`)
  }
}

export function assertBlocked(result, name) {
  const msg = result.error?.message || ''
  const isRls = msg.includes('row-level security') || msg.includes('violates row-level')
  if (isRls) {
    console.log(`  PASS  ${name} (correctly blocked)`)
    state.passed++
  } else if (result.error) {
    console.log(`  FAIL  ${name} — error but not RLS: ${msg}`)
    state.failed++
    state.failures.push(`${name}: non-RLS error: ${msg}`)
  } else {
    console.log(`  FAIL  ${name} — write was ALLOWED but should have been blocked`)
    state.failed++
    state.failures.push(`${name}: should have been blocked`)
  }
}

export function summary() {
  console.log()
  console.log(`${state.passed} passed, ${state.failed} failed`)
  if (state.failed > 0) {
    console.log('\nFailures:')
    state.failures.forEach(f => console.log(`  - ${f}`))
    process.exit(1)
  }
  process.exit(0)
}
